In [5]:
import sys
import os
import importlib
import numpy as np

#Add code paths
sys.path.append(os.path.abspath("../code/part3/"))

# Ex3
weights:
- w1 =  ( 1, 0,  0, 0, 0)
        (-1, 1, -1, 1, 0)
        ( 1, 1,  1, 1, 1)

- w2 =  (0, 0, 0)
        (2, 0, 0)

bias:
- b1 = (0,0,0)T
- b2 =   (0,0)T

input: 
- x1 = (1,1,1,1,1)T

target:
- t = (1,0)T

learning rate:
- r = 1

hidden layer:
- ReLU function = x if x>=0, 0 if x<0

output layer:
- SoftMax function = e^x / sum(e^xi)

error:
- cross-entropy error loss

In [6]:
w1_0 = np.array([1,0,0,0,0])
w1_1 = np.array([-1,1,-1,1,0])
w1_2 = np.array([1,1,1,1,1])
w1 = np.array([w1_0,w1_1,w1_2])

w2_0 = np.array([0,0,0])
w2_1 = np.array([2,0,0])
w2 = np.array([w2_0,w2_1])

b1 = np.transpose(np.array([0,0,0]))
b2 = np.transpose(np.array([0,0]))

x0 = np.transpose(np.array([1,1,1,1,1]))
t1 = np.array([1,0])

learning_rate = 1

## a) Do a stochastic gradient descent update and indicate the new weights and bias.  

In [7]:
import neural_network as nn
importlib.reload(nn) 

nn.learn(x0, t1, b1, b2, w1, w2, learning_rate, debug = False)

RESULTS
w1:
 [[-0.76159416 -1.76159416 -1.76159416 -1.76159416 -1.76159416]
 [-1.          1.         -1.          1.          0.        ]
 [ 1.          1.          1.          1.          1.        ]]
b1:
 [[-1.76159416]
 [ 0.        ]
 [ 0.        ]]
w2:
 [[ 0.88079708  0.          4.40398539]
 [ 1.11920292  0.         -4.40398539]]
b2:
 [[ 0.88079708]
 [-0.88079708]]
